services:
  - type: static
    name: whatsapp-clothing-admin-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    redirects:
      - source: "/*"
        destination: "/index.html"
        status: 200
    envVars:
      - key: VITE_SERVER_URL
        sync: false

